# Generated by Django 2.1 on 2018-08-13 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('project_name', models.CharField(max_length=255)),
                ('pub_date', models.DateTimeField(verbose_name='date published')),
                ('start_date', models.DateTimeField(verbose_name='starting date')),
                ('end_date', models.DateTimeField(verbose_name='ending date')),
                ('head', models.CharField(max_length=255)),
                ('content', models.CharField(max_length=255)),
                ('proj_id', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=255)),
                ('app_deadline', models.DateTimeField(verbose_name='application deadline')),
                ('num_places', models.PositiveIntegerField()),
                ('required_skills', models.CharField(max_length=255)),
                ('tags', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=255)),
                ('user_id', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('status', models.CharField(max_length=255)),
            ],
        ),
    ]
