# Generated by Django 2.1 on 2018-08-20 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='about_me',
            new_name='interests',
        ),
        migrations.AddField(
            model_name='profile',
            name='faculty',
            field=models.CharField(blank=True, choices=[('a', 'ApMath'), ('c', 'Chemistry'), ('p', 'Physics'), ('m', 'MathMech'), ('b', 'Biology'), ('l', 'Faculty of Law'), ('s', 'Social Faculty')], default=1, help_text='Faculty', max_length=1),
        ),
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, choices=[('b', 'Bachelor'), ('m', 'Master'), ('g', 'Graduate Student'), ('t', 'Teacher')], default=1, help_text='Status', max_length=1),
        ),
    ]
