# Generated by Django 2.1 on 2018-08-22 09:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appforproject',
            options={'permissions': (('view_application', 'Can see application'), ('approve_application', 'Can approve application'), ('reject_application', 'Can reject application'))},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('view_project_details', 'Can see project details'), ('edit_project', 'Can edit project'), ('approve_project', 'Can approve project'), ('reject_project', 'Can reject project'))},
        ),
    ]
