# Generated by Django 2.1 on 2018-08-14 08:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fairapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='skill',
            field=models.ManyToManyField(to='fairapp.Skill'),
        ),
        migrations.AddField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(to='fairapp.Tag'),
        ),
        migrations.AddField(
            model_name='project',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fairapp.Type', verbose_name='Category'),
        ),
    ]
