# Generated by Django 2.1 on 2018-08-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='brief_summary',
            field=models.CharField(default='Краткое описание', max_length=1000),
            preserve_default=False,
        ),
    ]
