# Generated by Django 2.1 on 2018-08-20 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairapp', '0002_auto_20180820_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='grade',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
