# Generated by Django 2.1 on 2018-08-22 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairapp', '0002_auto_20180822_1258'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='appforproject',
            options={'permissions': (('approve_application', 'Can approve application'), ('reject_application', 'Can reject application'))},
        ),
        migrations.AlterModelOptions(
            name='project',
            options={'permissions': (('approve_project', 'Can approve project'), ('reject_project', 'Can reject project'))},
        ),
    ]
