# Generated by Django 2.1 on 2018-08-27 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fairapp', '0002_auto_20180826_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='app_deadline',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='application deadline'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='ending date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=django.utils.timezone.now, verbose_name='starting date'),
        ),
    ]
