# Generated by Django 2.1 on 2018-08-14 09:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fairapp', '0002_auto_20180814_1135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='skill',
            field=models.ManyToManyField(related_name='skills', to='fairapp.Skill'),
        ),
        migrations.AlterField(
            model_name='project',
            name='tag',
            field=models.ManyToManyField(related_name='tags', to='fairapp.Tag'),
        ),
        migrations.AlterField(
            model_name='project',
            name='type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='fairapp.Type'),
        ),
    ]
