# Generated by Django 2.1 on 2018-08-27 07:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairapp', '0003_auto_20180827_0740'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='app_deadline',
            field=models.DateField(default=datetime.date.today, verbose_name='application deadline'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateField(default=datetime.date.today, verbose_name='ending date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateField(default=datetime.date.today, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateField(default=datetime.date.today, verbose_name='starting date'),
        ),
    ]
