# Generated by Django 2.1 on 2018-08-14 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairapp', '0003_auto_20180814_1242'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='brief_summary',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='content',
            field=models.TextField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='head',
            field=models.TextField(max_length=255),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_name',
            field=models.TextField(max_length=255),
        ),
    ]
