# Generated by Django 2.1 on 2018-08-22 13:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fairapp', '0003_auto_20180822_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, choices=[('m', 'Moderation'), ('c', 'Collecting participants'), ('p', 'In progress'), ('f', 'Finished'), ('r', 'Rejected')], default=1, help_text='Project status', max_length=1),
        ),
    ]
