# Generated by Django 2.1 on 2018-08-13 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fairapp', '0003_auto_20180813_1702'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
        migrations.RemoveField(
            model_name='project',
            name='proj_id',
        ),
    ]
