# Generated by Django 2.1 on 2018-08-27 07:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('fairapp', '0004_auto_20180827_0750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='app_deadline',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='application deadline'),
        ),
        migrations.AlterField(
            model_name='project',
            name='end_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='ending date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='pub_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='project',
            name='start_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='starting date'),
        ),
    ]
