# Generated by Django 2.1 on 2018-08-16 11:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fairapp', '0004_auto_20180814_1553'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppForProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('covering_letter', models.TextField(max_length=1000)),
                ('project', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='fairapp.Project')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
